server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:

  - job_name: nginx
    static_configs:
      - targets:
        - localhost
        labels:
          job: nginx
          __path__: /var/log/nginx/*json

  - job_name: app
    static_configs:
      - targets:
        - localhost
        labels:
          job: app
          __path__: /var/log/app/*log

  - job_name: worker
    static_configs:
      - targets:
        - localhost
        labels:
          job: worker
          __path__: /var/log/worker/*log

  - job_name: db
    static_configs:
      - targets:
        - localhost
        labels:
          job: db
          __path__: /var/log/db/*json