# Generated by Django 5.0.3 on 2024-03-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='weight',
            field=models.FloatField(default=-1.0),
        ),
    ]
