FROM python:3.12-alpine
RUN apk add build-base linux-headers
RUN apk cache clean
RUN mkdir /app
RUN adduser -D celery
RUN python -m venv /app/venv

COPY src /app/
COPY requirements/production.txt /app/requirements.txt
COPY worker.sh /app/
RUN chmod 755 /app/worker.sh
RUN mkdir /applogs

RUN chown -R celery /app /applogs
USER celery
ENV PATH="/app/venv/bin:$PATH"
RUN pip install -r /app/requirements.txt
ENTRYPOINT [ "/app/worker.sh" ]